src/shared/styles/palette.css

Добавлены css-переменные цветов. Ссылка на задачу в Notion:
https://www.notion.so/front-52aae4efcc1743f58f4abf64bf7357ff?p=333981cbe2004f8b9bf72a24a6c8e3f0

feat: добавить переменные цветов

---

src/components/ideology-text-item/ideology-text-item.tsx

Исправлена семантика заголовков в ветке ideology

fix: заменить h4 на h3 в TextItem

---

.storybook/preview.js
src/components/critique-card/critique-card.module.css
src/components/critique-card/critique-card.stories.tsx
src/components/critique-card/critique-card.tsx
src/components/critique-card/index.ts
src/components/review-card/index.ts
src/components/review-card/review-card.module.css
src/components/review-card/review-card.stories.tsx
src/components/review-card/review-card.tsx
src/components/review-carousel/index.ts
src/components/review-carousel/review-carousel.module.css
src/components/review-carousel/review-carousel.stories.tsx
src/components/review-carousel/review-carousel.tsx
src/components/ui/image-slider/image-slider.tsx
src/pages/_app.tsx
src/shared/types/common.ts
src/shared/types/index.ts

Добавление карусели рецензий

---

.editorconfig
src/components/ui/droplist/container-button/container-button.module.css
src/components/ui/droplist/container-button/container-button.tsx
src/components/ui/droplist/container-button/index.ts
src/components/ui/droplist/droplist-items/droplist-items.module.css
src/components/ui/droplist/droplist-items/droplist-items.tsx
src/components/ui/droplist/droplist-items/index.ts
src/components/ui/droplist/droplist.module.css
src/components/ui/droplist/droplist.stories.tsx
src/components/ui/droplist/droplist.tsx
src/components/ui/droplist/index.ts
src/components/ui/droplist/list-selected/index.ts
src/components/ui/droplist/list-selected/list-selected.module.css
src/components/ui/droplist/list-selected/list-selected.tsx
src/components/ui/droplist/utils/createList.ts
src/components/ui/droplist/utils/index.ts

Независимый компонент для выбора месяца и года пьесы. Имеет открывающий список для выбора, и кнопку.
__Props, входные параметры__:
* __type:__ тип выбора пьес. Какой droplist будете использовать. Обязательно указать,
* __handlerSubmitDroplist__: функция обработчик с одним параметром, в качестве параметра массив строк. 
Вызывается в момент onSubmit формы. Обязательно указать,
*  __data:__ массив строк или массив чисел. Передаете в случае, если нужно составить свой список для выбора, Необязательно, но лучше указать,
* __maxWidth__: ширина компонента "Droplist", и всех его элементов. Обязательно укажите свою ширину, по умолчанию она 300. Можно указать строкой '300', а можно указать числом 300. Необязательно,
*  __widthSelectedItem__: редко используется. Использовать если по какой-то причине …

Droplist. Список для выбора месяца и года пьесы.

---

src/components/ui/announced-play-card/announced-play-card.module.css
src/components/ui/announced-play-card/announced-play-card.tsx

- добавлен пропс для добавления кастомного стиля в карточку пьесы в афише событий 
- фикс: убрано добавление нижнего бордера у последнего элемента announced-play-card

Announced-play-card: Добавление возможности кастомного стиля

---

src/components/creators-list/creators-list.module.css
src/components/creators-list/creators-list.stories.tsx
src/components/creators-list/creators-list.tsx
src/components/creators-list/index.ts

Список создателей пьесы
[Сверстать блок команды пьесы](https://www.notion.so/front-52aae4efcc1743f58f4abf64bf7357ff?p=aa56743dd60444a0bfffc4490dfc9522)

Creators list

---

src/components/main-page/platforms/main-platforms.module.css
src/components/main-page/platforms/main-platforms.tsx
src/shared/styles/mixins/headline.css
src/shared/styles/mixins/text.css

Исправил отображение блока
[main-platforms](https://www.notion.so/main-platforms-a929df3f367e4cdbb5fc9c7e51494cef)

fix/Исправил отображение блока

---

src/components/main-page/archive/main-archive.tsx

У кнопки шрифт уходил
[main-archive](https://www.notion.so/main-archive-caa9cae1c718485dbdc1c80f429236ce)

fix/Поправил отображение кнопки

---

src/components/app-layout/app-layout.tsx
src/components/page/burger-button/index.ts
src/components/page/burger-button/page-burger-button.module.css
src/components/page/burger-button/page-burger-button.tsx
src/components/page/page.tsx

В этом ПР, компонент BurgerButton:
- Спозиционирован согласно макету
- Добавлена логика открытия OverlayNav по клику
Скрины (414px):

Открытие OverlayNav по клику на BurgerButton

---

src/components/app-layout/app-layout.stories.tsx
src/shared/helpers/scale.js

Исправление вызовов scale внутри transform

Фильтрация вызовов хелпера scale внутри transform

---

src/components/app-layout/app-layout.stories.tsx
src/components/ui/basic-play-card/basic-play-card.tsx
src/components/ui/basic-play-card/list/basic-play-card-list.stories.tsx
src/components/ui/text-area/index.ts
src/components/ui/text-input/text-input.stories.tsx
src/pages/afishe/index.tsx
src/pages/author/index.tsx
src/pages/project/index.tsx
src/pages/success-page/index.tsx

`npm run build` не запускался, так как были ошибки в типах и импортах/экспортах. Тем самым, не получалось сделать билд и деплой не может работать.
В этом PR эти моменты исправлены

fix: Фиксы импортов/экспортов и типов для работы прод билда

---

src/components/navbar/help-link/navbar-help-link.module.css
src/components/navbar/section/navbar-section.module.css
src/components/ui/menu/type/social-links.module.css

Добавляет hover для ссылок на соцсети и кнопку в шапке
[Привести ссылки шапки к дизайну](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=eb6afa1868e64ba284e56c67f2d772b8)

Social links hover

---

src/components/author-page/another-plays/another-plays.module.css
src/components/author-page/another-plays/another-plays.tsx
src/components/author-page/information/information.module.css
src/components/author-page/information/information.tsx

Рефакторинг двух компонентов для страницы автора:
- добавлен $tablet-portrait,
- убраны лишние стили,
- доделан и подключён компонент Ссылки для таблицы,
- Изменён размер Button для скачивания,
[Рефакторинг двух компонентов](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=7bb3744b57e34bed95367799db43fcb3)

Refactor another-plays component & information component

---

src/components/ui/droplist/droplist.tsx

Исправляю баг в интерфейсе className

fix/подправил интерфейс className

---

package-lock.json
package.json
src/components/main-page/title/main-title.module.css
src/components/page/overlay/page-overlay.tsx
src/components/ui/modal/backdrop/index.ts
src/components/ui/modal/backdrop/modal-backdrop.module.css
src/components/ui/modal/backdrop/modal-backdrop.tsx
src/components/ui/modal/index.ts
src/components/ui/modal/modal.module.css
src/components/ui/modal/modal.stories.tsx
src/components/ui/modal/modal.tsx
src/components/ui/portal/index.ts
src/components/ui/portal/portal.tsx
src/shared/hooks/use-disable-body-scroll.ts
src/shared/styles/palette.css

Компонент Modal. 
Реализованы основные требования к доступности:
- При открытии блокирует скролл основного контента страницы
- При открытии фиксирует фокус
- Закрытие по Esc
- Опциональный бэкдроп, при клике закрывает модалку
- Базовые aria атрибуты
По хорошему, нужно еще скрывать от скринридеров остальной контент сайта, но уже не в рамках этой задачи.
Помимо всего, при монтировании компонент помещается в конец body с помощью портала.
Предполагается для использования в попапах. @in-the-garden 👀
https://lubimovka-frontend-2tdnrnqey-lubi.vercel.app/
[Реализовать компонент модального окна](https://www.notion.so/f33b2344797b47569849514b1d3ce351)

Добавление компонента Modal

---

src/components/ui/burger-button/burger-button.module.css
src/components/ui/burger-button/burger-button.tsx

* Подредактировала компонент мобильного меню
* Добавила анимацию
_не уверена стоит ли заморачиваться доступностью с клавиатуры(tabindex, keyboard event handler), поскольку кнопка подразумевается только на планшетах и мобильных_
в продолжение задачи [Сверстать кнопку мобильного меню](https://www.notion.so/eda7d1f8e218454b9f2dca757a86512c) в соответствии с [ответом дизайнера](https://www.notion.so/dfcafac15d844cc3ac45569a4f43b87e)

Добавление анимации кнопке мобильного меню

---

.env.local
.gitignore

Удаление файла с переменными окружения из репозитория

Удаление файла с переменными окружения из репозитория

---

src/components/ui/basic-play-card/basic-play-card.module.css
src/components/ui/basic-play-card/basic-play-card.stories.tsx
src/components/ui/basic-play-card/basic-play-card.tsx

Reverts Studio-Yandex-Practicum/lubimovka_frontend#128

Revert "basic-play-card: рендеринг нескольких авторов"

---

src/components/ui/person-card/person-card.module.css
src/components/ui/person-card/person-card.tsx

Раньше кнопка отзыва у волонтера скейлилась, а иконка в кнопке нет, теперь все скейлится пропорционально.

fix: поправить скейл иконки на кнопке отзыва у волонтера

---

src/components/library-authors-page/index.module.css
src/components/library-authors-page/index.tsx
src/components/library-form/library-form.module.css
src/components/library-form/library-form.tsx
src/components/library-pagination/library-pagination.module.css
src/components/library-pagination/library-pagination.tsx
src/components/library-pieces-page/index.module.css
src/components/library-pieces-page/library-filters-modal/index.module.css
src/components/library-pieces-page/library-filters-modal/index.tsx

Поправила вёрстку элементов с позиционированием sticky на страницах library и library/authors
[Доработать вёрстку "липких" элементов (поведение при скролле) у /library и /library/authors](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=d378633875e7498087d1d72f579d733a)

Fix library sticky

---

src/components/participation-form/participation-form.tsx
src/components/ui/form/form.stories.tsx
src/components/ui/text-area/text-area.module.css
src/components/ui/text-area/text-area.stories.tsx
src/components/ui/text-area/text-area.tsx
src/components/ui/text-input/text-input.module.css
src/pages/contacts.tsx
src/pages/form.tsx
src/shared/regexps.ts

Добавлены
* валидация формы обратной связи
* блокировка отправки, если форма невалидна
* состояние успешной отправки
* рефакторинг компонента TextArea
также поправлены стили полей при фокусе, улучшены проверки номера телефона и имени файла пьесы
[Оживить отправку формы на странице «Контакты»](https://www.notion.so/f9fbedf819e648cfae461b4d3c0430b8)

Оживить отправку формы на странице «Контакты»

---

src/components/ideology-page/index.module.css
src/components/ideology-page/index.tsx
src/components/ideology-section/ideology-section.tsx
src/components/ideology-text-item/ideology-text-item.tsx
src/pages/ideology/index.module.css
src/pages/ideology/index.tsx

Добавила на страницу идеологии навигационное меню AboutUsMenu из [PR](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/140#issue-1052373956)
[Добавить на идеологию субменю](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=d627a322b8c243c9a13177348de5ad08)

Submenu for ideology

---

src/components/page-transition/index.ts
src/components/page-transition/page-transition.module.css
src/components/page-transition/page-transition.tsx
src/components/participation-form/participation-form.tsx
src/pages/form-success.tsx
src/pages/form.tsx

* добавлен компонент `PageTransition`
* добавлена анимация при открытии страницы успешной отправки формы пьесы (только на мобилке)
* удалены ненужные состояния успешной формы отправки пьесы
[Оживить экран успешной подачи пьесы](https://www.notion.so/7d8ec5b80d8e4e24b9aedfb2a30fbf0f), чтобы было [так](https://www.figma.com/proto/zpyHTGb3aKiAbpJJoIVqQ2/lubimovka?node-id=912%3A14861&scaling=scale-down&page-id=912%3A14271&starting-point-node-id=912%3A14861&show-proto-sidebar=1)

Оживление экрана успешной подачи пьесы

---

src/components/ui/droplist/droplist.tsx

Вернул код который удалил.
[droplist (2 типа)](https://www.notion.so/droplist-2-ffcb553288ba45c69aa5e517be47adf7)

fix/droplist. Возвращаю нужный код

---

src/components/author-page/request/request.module.css
src/components/author-page/request/request.tsx

Небольшой компонент для отправки сообщений о внесении изменений об авторах Любимовки на странице Автора.
[Request Component](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=e11dd76455f841b08db5cd77e116d982)

Request Component

---

src/components/app-layout/app-layout.tsx
src/components/donation-link/donation-link.module.css
src/components/footer-partner-list/footer-partner-list.module.css
src/components/footer/address/footer-address.module.css
src/components/footer/footer.module.css
src/components/footer/footer.tsx
src/components/footer/logo/index.ts
src/components/footer/logo/logo.module.css
src/components/footer/logo/logo.tsx
src/components/footer/navigation/footer-navigation.module.css
src/components/footer/partners/footer-partners.module.css
src/components/footer/projects/footer-projects.module.css
src/components/navbar/actions/navbar-actions.module.css
src/components/navbar/logotype/navbar-logotype.module.css
src/components/navbar/navbar.module.css
src/components/navbar/section/navbar-section.module.css
src/components/page/header/page-header.module.css
src/components/ui/menu/type/main-navigation.module.css
src/shared/styles/vars.css

Добавление компонента Footer в PageOverlay.
Правка верстки компонента Navbar в соответствии с макетом/
Правка медиазапросов для корректной работы страниц на на 768px
1)[Добавить footer в мобильную навигацию + поправить отступы в шапке](https://www.notion.so/footer-b7943032991148f49fa5a92a8307bb43)
2)[Отрефакторить стили шапки](https://www.notion.so/c53a0fa1f65c47c69e6f6fb72e41ae3b)

Правка верстки компонентов PageOverlay и Navbar в соответствии с макетом 

---

.env.local
src/components/library-filter/library-filter.tsx
src/pages/library/index.tsx
src/pages/library/library-query-parser.ts

Добавлено отображение выбранных фильтров в адресной строке в разделе библиотеки
[Библиотека. Добавить отображение выбранных фильтров в адресной строке](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=0c9b37c27d594075882367577f67aa63)

Library query url

---

src/components/article-page/article-page.tsx
src/mocks/data/blogArticle.ts
src/mocks/data/newsArticle.ts
src/shared/types/article-types.ts

Мини доработка в связи с [обновлением схемы страницы от бэка](https://yandex-students.slack.com/archives/C02D437F23F/p1639012288250100)
Добавляем в карточки персон описание(роли) каждой персоны.

ArticlePage:  добавить описание(роли) каждой персоны в ответ бэка по Personsblock

---

.github/workflows/deploy-ci.yml

Добавлены изменения в action CI для обновления образа докер на сервере.
Необходимо добавить environments к вам в репозиторий

add job in CI action, deploy in server

---

src/components/library-authors-page/index.tsx
src/components/library-pieces-page/index.tsx

Добавила выделение табов в меню в библиотеке в зависимости от текущей страницы (пьесы или авторы)
[Поправить табы пьесы/авторы на странице библиотеки](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=efe2e4b55280478c9ee2fbf3d716cf5c)

Fix library menu

---

src/components/404/NotFoundError.tsx
src/components/author-page/overview/overview.tsx
src/components/author-page/plays/plays.tsx
src/pages/authors/[id].tsx

Добавление адреса к API для фетчера.
Исправления по мелочи на странице Автора.

refactor: Added new url for fetcher on Author page

---

src/components/404/NotFoundError.module.css

Добавляет ховер-эффект для ссылок на странице 404
[Добавить ховер-эффект для ссылок на странице 404](https://www.notion.so/404-9341908ac994458c97cd2a092445e4dd)

fix: добавить ховер-эффект для ссылок на странице 404

---

src/components/library-authors-page/index.module.css
src/components/library-authors-page/index.tsx
src/components/library-pieces-page/index.module.css
src/components/library-pieces-page/index.tsx

Починила табы библиотеки согласно замечаниям QA
[Поправить отображение табов](https://www.notion.so/Frontend-52aae4efcc1743f58f4abf64bf7357ff?p=7490572fa6a7495aa41b4014071f4db8)

Library fix tabs

---

src/mocks/data/main.ts

Добавил в mocks/main в first_screen поле image
[Исправить ошибки ts](https://www.notion.so/ts-e05d5079b9994368929a2472fba2f052)

fix/Добавил в mocks/main в first_screen поле image

---

src/shared/constants/api-path.js

This reverts commit 8888aa39955798a298825b79ce6d68e37bd25ad3.

Revert "chore: тестовое изменение префикса проксирования api"

---

src/pages/index.tsx

Поменял функцию сборки на getServerSideProps
[main fix getServerSideProps](https://www.notion.so/main-fix-getServerSideProps-117f483742ec46f78c6415a450409a93)

Page main api

---

src/components/partners/partners.module.css
src/components/partners/partners.tsx

Убрал padding и width. Добавил props className
[Добавить партнеров fix](https://www.notion.so/fix-806c76ba15ee4133b0e255003c9bc402)

fix/Убрал padding и width. Добавил props className

---

src/components/afisha-page/festival-day/afisha-festival-day.tsx

Исправлены ошибки для корректной сборки

Афиша: Исправлены ошибки для корректной сборки

---

src/components/ui/tag/tag.module.css
src/components/ui/tag/tag.tsx

Добавляет функцию scale в css
[Ссылка на pull requests](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/pull/18)
[Tags (scale)](https://www.notion.so/Tags-scale-906097b7aafd4f439bc0c3dcaf2570c4)

Refactoring tags

---

src/components/library-filter/library-filter-reducer.ts
src/components/library-filter/library-filter.tsx
src/components/library-pieces-page/index.tsx
src/components/library-tags-mobile/library-tags-mobile.tsx
src/mocks/data/playfilters.ts
src/pages/library/index.tsx

Адаптировал страницу библиотеки под новый droplist

fix: Адаптировал страницу библиотеки под новый droplist

---

src/components/main-page/title/main-title.tsx
src/pages/index.tsx

Решает ошибку
[При переходе на главную страницу выходит ошибка 500](https://www.notion.so/500-000bbf9a168741ce8628733dcbcf7db7)

refactor: Заменить title на статический текст

---

src/components/library-pieces-page/index.module.css

Поправил мобильную поисковую строку
[Поправить мобильный фильтр библиотеки](https://www.notion.so/4b33530b19c44b1aa1151e3bd16a486a?v=8c8d21f168d64034a42b6a0c20c86db6&p=8d9586e52fab43ddaa63c59815a0c013)

fix: поправил мобильную поисковую строку

---

src/components/library-pieces-page/index.module.css

Добавляет возможность клика/тапа по авторам в карточках пьес странице библиотеки на мобильном разрешении
[Поправить кликабельность карточек в мобильной библиотеке](https://www.notion.so/f9260a4d07784fb882e5650673cb828a)

fix: добавить возможность клика (или тапа) по авторам

---

src/components/author-page/overview/overview.module.css
src/components/author-page/plays/plays.module.css

При недостатке данных обнаружился баг в сетке вёрстки, теперь он исправлен.
[Поправить отступы в вёрстке](https://www.notion.so/Frontend-52aae4efcc1743f58f4abf64bf7357ff?p=54e3538f5db84047b5b5a5ddab9c98af)

Страница Автора, исправление вёрстки

---

next.config.js

refactor/Добавить домены к картинкам

---

src/components/history-page/history-page.tsx
src/components/history-page/itself/history-itself.module.css
src/components/history-page/title/history-title.tsx
src/pages/history/index.tsx

Устранил ошибки в мобильной верстке. Добавил ссылки кнопкам, в зависимости от информации которая приходит с бэка.
[Рефакторинг страницы история](https://www.notion.so/Frontend-52aae4efcc1743f58f4abf64bf7357ff?p=d0ef6c3ae0c344b8a5d221867961585a)

Рефакторинг страницы История

---

src/components/article-page/article-page.tsx
src/components/author-page/plays/plays.tsx
src/components/library-pieces-page/index.tsx
src/components/main-page/shortList/main-shortList.tsx
src/components/ui/basic-play-card/basic-play-card.module.css
src/components/ui/basic-play-card/basic-play-card.stories.tsx
src/components/ui/basic-play-card/basic-play-card.tsx
src/pages/library/search-result/index.tsx
src/pages/performances/[id].tsx
src/pages/projects/[id].tsx

refactor: компонента: basic-play-card
Появилась ошибка ts после обновления данных на сервере
[refactor: компонента: basic-play-card](https://www.notion.so/refactor-7e1715aa76be45d1b2d5b50f43fac24e)

Рефакторинг карточки пьесы

---

src/components/search-result-authors/search-result-authors.tsx
src/mocks/data/blogArticle.ts
src/mocks/data/newsArticle.ts
src/pages/library/search-result/index.tsx

Описание
Для автора во всем проекте заменено id на slug
Ссылка на задачу
[Автор id⇒slug](https://www.notion.so/id-slug-69ff61206c934ccf9b50e5861be15c70)

Переделать Author с id на slug

---

src/components/library-authors-page/index.tsx
src/components/library-pagination/library-pagination.tsx
src/components/library-pieces-page/index.module.css
src/pages/library/authors.tsx

Добавил загрузку авторов при клике на букву
[Доработка фильтрации на странице авторов](https://www.notion.so/4b33530b19c44b1aa1151e3bd16a486a?v=8c8d21f168d64034a42b6a0c20c86db6&p=32b9d3ccb6904b969360455a156811e1)

feature: добавил загрузку авторов при клике на букву

---

src/components/library-authors-page/index.tsx
src/components/library-pagination/library-pagination.module.css
src/components/library-pagination/library-pagination.tsx
src/components/persons-list/persons-list.module.css
src/components/persons-list/persons-list.tsx
src/components/team-page/art-directorate/section/art-directorate-section.module.css
src/components/team-page/volunteers/list/volunteers-list.tsx
src/components/ui/feedback-popup/feedback-popup.module.css
src/pages/library/authors.tsx

fix: поправил кнопки

---

src/components/what-we-do-page/contacts/what-we-do-contacts.module.css
src/components/what-we-do-page/contacts/what-we-do-contacts.tsx
src/pages/what-we-do/index.tsx

Небольшие исправления для страницы "Что мы делаем?"
[Выводить партнеров только когда они приходят с сервера](https://www.notion.so/d88e32232c8245078ca3d8f9dc467b86)
[Менять цвет фона шапки в мобильной версии.](https://www.notion.so/2a5066703de34033a202b955ed98bd88)
[Добавить ui компонент для ссылки. Стилизовать его](https://www.notion.so/ui-fd01bab7cbe4463c91234f122970f765)

What we do qa fix

---

src/components/blog-layout/blog-layout.module.css
src/components/news-layout/news-layout.module.css
src/pages/blog/blog.tsx
src/pages/news/news.tsx

Добавлено сообщение о том, что ничего не найдено, на страницах блога и новостей
[Добавить сообщение о том, что ничего не найдено на страницы блога и новостей](https://www.notion.so/f7f52476efed4a0a84394d5e3aec6a1e)

Добавление сообщения о том, что ничего не найдено, на страницах блога и новостей

---

src/components/participation-form/participation-form.module.css
src/components/play-proposal-layout/column/play-proposal-layout-column.module.css
src/components/ui/file-input/file-input.module.css
src/components/ui/form/actions/form-actions.module.css
src/components/ui/form/disclaimer/form-disclaimer.module.css

правит верстку формы на странице подачи пьесы
[На странице "Подать пьесу" кнопка “Отправить” смещена влево](https://www.notion.so/ce40342e7eb346e08639f719e2e064ce)

Исправление верстки формы подачи пьесы

---

next.config.js

fix: добавлен домен картинок lubimovka.art
Без задачи

fix: добавлен домен картинок lubimovka.art

---

infra_deploy/stage/lubimovka_frontend_stage_deploy.yml
public/robots.txt

Переход на новую версию swag, добавление файла robots.txt

---

infra_deploy/stage/lubimovka_frontend_stage_deploy.yml

Переход с zerossl на letsencrypt

---

src/components/constructor-content/constructor-content.tsx
src/components/performance-section/performance-section.module.css
src/components/performance-section/performance-section.tsx
src/components/section/section.module.css
src/components/section/section.tsx

Добавлены отступы у блоков контента конструктора
[Привести блок контента конструктора на странице проекта к дизайну](https://www.notion.so/b9655b7ba37c47678d8a372690341e96)

Приведение блока контента конструктора на странице проекта к дизайну

---

src/components/app-layout/app-layout.tsx
src/components/partner-list/item/partner-list-item.module.css
src/components/partner-list/item/partner-list-item.tsx

Добавление модификатора вида (type_expanded) компоненту списка партнеров в соответствии с дизайном для использования на главной и странице "Что мы делаем".
[Привести список партнеров к дизайну](https://www.notion.so/57b47b2d312d4a8da8938a5443707912)

Приведение списка партнеров к дизайну

---

infra_deploy/stage/lubimovka_frontend_stage_deploy.yml

Монтирование логов в каталог /LUBIMOVKA/logs

---

infra_deploy/stage/lubimovka_frontend_stage_deploy.yml

Перенос папки media с volume в корень проекты (/LUBIMOVKA)

---

infra_deploy/stage/lubimovka_frontend_stage_deploy.yml

Исправление ошибки с переменной SUBDOMAIN

---

src/api-typings/index.ts
src/api-typings/models/Achievement.ts
src/api-typings/models/AuthorRetrieve.ts
src/api-typings/models/OtherLink.ts
src/components/author-page/information/information.tsx
src/components/author-page/overview/overview.tsx

Обновление API страницы авторов. Обновил тайпинги авторов и код, использующий их
[500 на странице авторов](https://www.notion.so/QA-frontend-08af2ea1f509419b9277079fa887e01e?p=8c5f4b3b3acb48b3b114bd86e8b04e42)

fix: исправление после изменения api

---

Dockerfile
README.md
config/vars.js
docker-entrypoint.sh
infra_deploy/stage/lubimovka_frontend_stage_deploy.yml
next.config.js
package.json
src/shared/helpers/url.ts

Reverts Studio-Yandex-Practicum/lubimovka_frontend#386

Revert "Быстрофикс url клиентских запросов"

---

src/components/author-page/overview/overview.tsx
src/components/library-authors-page/index.tsx
src/components/library-form/library-form.tsx
src/components/library-pagination/library-pagination.tsx
src/components/ui/tag/tag.module.css
src/mocks/data/playfilters.ts
src/pages/library/authors.tsx
src/pages/library/index.tsx

Исправил парсинг квери параметров

fix: исправление библиотеки и авторов

---

src/api-typings/models/Festival.ts
src/components/history-page/header/history-header.tsx
src/components/history-page/history-page.tsx
src/components/history-page/title/history-title.tsx
src/pages/history/index.tsx
src/pages/library/index.tsx

Правки по библиотеке и истории
[Скрывать разделы “Дополнительно” и “Ссылки”, если приходит пустой массив /history](https://www.notion.so/query-history-94f00bc355c04f4a89a08b95812e5872)
[Добавить в query параметры /history выбранный год](https://www.notion.so/Frontend-52aae4efcc1743f58f4abf64bf7357ff?v=84023778e1024506b75f0af4321bfba2&p=035c07a301a447c1816499ce90cd5153)

Library fix

---

postcss.config.js
src/components/donation-page/donationPageTitle/donationPageTitle.module.css
src/components/donation-page/donationPageTitle/donationPageTitle.tsx

Reverts Studio-Yandex-Practicum/lubimovka_frontend#399

Revert "Исправление масштабирования виджета поддержки фестиваля"

---

src/components/history-page/title/history-title.tsx

меняется текст * пьес прозвучало на фестивале
[Правка в тексте на странице История](https://www.notion.so/2184c03a20c84495af6912a5e9251bf1)

Правка в тексте на странице «История»

---

src/api-typings/models/LocalEvent.ts
src/components/performance-event-list/item/performance-event-list-item.tsx
src/components/performance-headline/performance-headline.module.css
src/components/performance-headline/performance-headline.tsx
src/components/performance-layout/bottom-image/performance-layout-bottom-image.module.css
src/components/performance-layout/cover/index.ts
src/components/performance-layout/cover/performance-layout-cover.module.css
src/components/performance-layout/cover/performance-layout-cover.tsx
src/components/performance-layout/events/index.ts
src/components/performance-layout/events/performance-layout-events.module.css
src/components/performance-layout/events/performance-layout-events.tsx
src/components/performance-layout/gallery/performance-layout-gallery.module.css
src/components/performance-layout/intro/index.ts
src/components/performance-layout/intro/performance-layout-intro.module.css
src/components/performance-layout/intro/performance-layout-intro.tsx
src/components/performance-layout/media-reviews/performance-layout-media-reviews.module.css
src/components/performance-layout/performance-layout.module.css
src/components/performance-layout/performance-layout.tsx
src/components/performance-layout/performance-layout.vars.module.css
src/components/performance-layout/reviews/performance-layout-reviews.module.css
src/components/performance-layout/share/performance-layout-share.module.css
src/pages/performances/[id].tsx

- Добавлено css свойство grid-template-columns к основному контейнеру спектакля для равной ширины столбцов контента
- Исправлен баг, связанный с изменением свойства url в api, который используется в формировании ссылки на покупку билетов
[О спектакле. Разная ширина у блоков изображение, описание, видео, пьеса](https://www.notion.so/94b2ae96a6614ddeb13610a93822c2a9)

Рефакторинг раскладки страницы спектакля

---

src/components/performance-layout/performance-layout.module.css
src/components/play-card/play-card.tsx
src/pages/performances/[id].tsx

Исправление размера с помощью модификатора
[Исправить размер карточки пьесы на странице спектакля](https://www.notion.so/Frontend-52aae4efcc1743f58f4abf64bf7357ff?p=20554e87bae24e8c84b6f5e5359252a7&pm=s)

Исправить размер карточки пьесы на странице спектакля 

---

public/robots.test.txt

Добавлен файл robots.txt для тестового окружения
https://www.notion.so/Robots-txt-nginx-006ffd4dd80c45a3b03dd732e92c91b4

Add robots.txt file for test environments

---

src/components/play-proposal-success-layout/play-proposal-success-layout.tsx

изменено сообщение о успешной отправке пьесы
[Поменять текст который высвечивается после отправки пьесы](https://www.notion.so/Frontend-52aae4efcc1743f58f4abf64bf7357ff?p=77acd109ae7a4379a3b37bcdf08dfea0&pm=s)

fix: изменено сообщение о успешной отправке пьесы

---

src/components/ui/text-area/text-area.module.css
src/components/ui/text-area/text-area.tsx
src/pages/contacts/contacts.tsx
src/services/fetcher/fetcher.ts

На странице контакты. Поле "Текст сообщение" можно сильно растянуть или сузить. Добавлены стили в компонент TextArea ограничивающие высоту и ширину поля.
[На странице контакты. Поле "Текст сообщение" можно сильно растянуть или сузить](https://www.notion.so/241711121ba54c1a981cd37820d39596)

fix: исправление поля текст сообщения на странице контакты

---

src/components/share-links/share-links.tsx

Исправлено поведение внешних ссылок

---

src/components/main-header/main-header.module.css

Поправила вёрстку главной страницы, чтобы в адаптиве не выбивалось за края экрана.
№1 в общем списке: На главной странице при вертикальном расположении телефона верстка не адаптируется (мобильная версия)

Bugfix / fix adaptive

---

src/pages/contacts/contacts.tsx

Исправлена повторная отправка сообщений на странице Контакты

---

src/components/history-page/title/history-title.module.css

Исправить верстку ссылок на пьесы в Истории

---

src/pages/blog/blog.tsx
src/services/api/blog-adapter.ts

Настроен функционал сортировки статей за месяц без выбора года

---

src/pages/about-us/sponsors/index.tsx

Исправить текст в разделе О фестивале - Попечители

---

src/pages/form/form.tsx

Исправила баги 81, 82, 83 из общего списка
Отсуствует ошибка валидации при пустом ввода в поле "Название" формы подачи пьесы
Отсуствует ошибка валидации при вводе менее 2 символов в поле "Название" формы подачи пьесы
Отсуствует ошибка валидации при вводе более 60 символов в поле "Название" формы подачи пьесы

Валидация формы подачи пьесы

---

src/components/app-layout/app-layout.tsx
src/shared/constants/social-link-items.ts

Сделать плитку ссылки на YouTube на 1 шаблонное место

---

src/components/ui/menu/type/footer-project-list.module.css

Исправить анимированное подчеркивание ссылок в футере секция проекты

---

src/components/404/NotFoundError.tsx

Убрать кнопку Подать пьесу на странице 404

---

src/shared/constants/novice-author-list-items.ts

Удалить авторов из списка на странице О фестивале

---

src/components/app-layout/app-layout.tsx
src/components/ui/menu/item/menu-item.tsx

Добавить настройку, чтобы соцсети загружались в новой вкладке браузера

---

src/components/what-we-do-page/contacts/what-we-do-contacts.tsx

Исправить верстку (div внутри p) на странице О фестивале раздел Контакты

---

src/components/video/video.tsx

Исправить url для показа видео на странице Блога

---

src/pages/form/form.tsx

Добавить проверку текстовых полей формы на верный формат

---

src/shared/constants/main-navigation-items.ts

Убрать Блог из главного верхнего меню

---

src/core/participation/types.ts
src/pages/form/form.tsx
src/services/api/participation.ts

Добавить поле Псевдоним в форму подачи пьесы

---

src/shared/constants/main-navigation-items.ts

Добавлена ссылка About the project в главное меню

---

src/pages/form/form.tsx

Исправлена валидация отправки формы, поле псевдонима скрыто

---

src/pages/form/form.tsx

- Убрал обязательность поля псевдоним при нажатом флаге анонимности

fix: добавление исключений валидации формы v2

---

src/components/festival-event-card/festival-event-card.tsx
src/components/festival-schedule/festival-schedule.tsx
src/core/schedule/types.ts
src/services/api/schedule-adapter.ts

Pull Request добавляет поле actionText в компоненте FestivalEventCard, для отображения текста в кнопке действия. 
[Текст на кнопке действия в афише всегда "Регистрация" #574](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/574#issue-2503235353)

Bugfix festival schedule action text

---

src/__generated__/api-typings/models/Project.ts
src/components/project-layout/description/project-layout-description.tsx
src/core/project/types.ts
src/pages/projects/[id].tsx
src/services/api/projects.ts

Pull Request заменяет статический заголовок о проекте на динамический, на странице проекты.
[На странице проекта вместо строки "О проекте" печатать строку, выдаваемую API #559](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/559)

Bugfix project description

---

src/pages/form/form.tsx

- Добавил фильтрацию параметра nickname перед отправкой формы, в зависимости от флага anonym

fix: добавление фильтрации параметра nickname формы

---

src/components/constructor-content/constructor-content.const.ts
src/components/constructor-content/constructor-content.tsx
src/components/constructor-content/constructor-content.utils/index.ts
src/components/constructor-content/section/constructor-content-section.tsx
src/components/constructor-content/variant/default.module.css
src/components/embed-code/embed-code.tsx
src/components/embed-code/index.ts

Фронтенд ожидает в ответах API блок конструктора с кодом вставки внешнего контента вида:
```js
{
content_type: 'embedcode',
content_item: {
title: 'Трейлер', // необязательный
code: '<iframe src="https://player.mave.digital/?podcast=lubimovka-podcast&episode=4&color=rgb(84,76,166)&mute=1&date=1&download=1" style="width: 100%" height="235" scrolling="no" frameborder="no"></iframe>',
}
}
```

Добавление блока конструктора для встраивания внешнего контента
