Studio-Yandex-Practicum/lubimovka_frontend

- src/components/ui/button/button.module.css
- src/components/ui/button/button.stories.tsx
- src/components/ui/button/button.tsx
- src/shared/styles/mixins/text.css
Небольшой рефакторинг компонента button.
- Теперь нет параметра view: 'transparent', а прозрачный фон - часть vew: 'primary'
- Использовал 'classnames / bind' для формирования списка классов
- Добавил 3 общих миксина в text.css, чтобы можно было централизованно управлять текстовыми стилями кнопок. 
- @textButton, общий для всех кнопок с единственным значением text-transform: uppercase;
- @textSmallButton 16 / 14, так как того же стиля не было в других текстовых миксинах
- @textLargeButton копирует @textSmall
- Исправлена ошибка, по которой не передавался параметр фиксированной ширины **width**, когда компонент **button** является ссылкой.
- Изменён способ форматирования внутри кнопки на **grid**
- Новые свойства компонента:
- **gap** - задаёт в пикселях отступ между иконкой и текстом. …
> Refactor: Button

- package-lock.json
- package.json
Обновление eslint-plugin-react до версии 7.26.1.
До этого обновления линтер выдавал ошибку, если неявно использовать children в компоненте с аннотацией типа React.FC. С учетом того, что в типе React.FC предусмотрен опциональный children, такое поведение вводит в заблуждение. Обновление убирает эту ошибку.
После вливания этой ветки рекомендую:
1. Удалить файл кэша линтера `.eslintcache`
2. Рестартануть eslint server
В ином случае, могут быть ошибки при выполнении команды `npm run lint:js`.
> Обновление eslint-plugin-react до версии 7.26.1

- src/components/ui/announced-play-card/announced-play-card.module.css
- src/components/ui/announced-play-card/announced-play-card.stories.tsx
- src/components/ui/announced-play-card/announced-play-card.tsx
**Обновление логики компонента announced-play-card:** 
добавлена логика рендеринга компонента, когда приходит пустой массив с именами режиссера/ов и драматургов/а, но приходит подробное описание мероприятие (`eventDescription`). состояние в макете: 
NB 📝 массив драматургов и режиссеров (`playwrightArray` и `directorArray`) я оставляю обязательным полем в интерфейсе, но проверяю длину массива. 
**Другие фиксы** 
1. исправлена семантика компонента `li > article `
2. упрощена запись для кнопки `isLink={true}`
3. фиксы лейаута по макету (добавлен больший отступ над названием пьесы в случае, если не приходит картинка-обложка)
UPD 16.10 
4. поправлено именование стилей 
5. исправлен брейкпойнт для мобильной версии - теперь мобильная версия отображается на tablet-portrait 
UPD 17.10 
6. …
> Announced Play Card fix - WIP

- src/components/ui/menu/type/history.module.css
Исправление ошибки - не работал скролл на странице History в компоненте Menu.
[Добавить скролл в компонент Menu для использования на странице History](https://www.notion.so/front-52aae4efcc1743f58f4abf64bf7357ff?p=702d44226fc14dfab3f578e93788d3b6)
> History page fix

- src/components/for-press-hero-title/assets/mock-data.json
- src/components/for-press-hero-title/for-press-hero-title.module.css
- src/components/for-press-hero-title/for-press-hero-title.stories.tsx
- src/components/for-press-hero-title/for-press-hero-title.tsx
- src/components/for-press-hero-title/index.tsx
Создан компонент с заголовком и описанием страницы О прессе. 
[pro-press-hero-title](https://www.notion.so/for-press-hero-title-c272d44bf81b4a528d6df9025f2f5a41)
UPD 28.10
Ошибки Typescript больше не наблюдается
1. есть ошибка TypeScript в stories, у `data` (думаю, как пофиксить)
```
Default.args = {
data: mockData,
};
```
> Type '{}' is missing the following properties from type '{ title: string; description: string; link: string; }': title, description, linkts(2739)
2. в целом пока сложность представить резиновость сайта. Использовала миксины, в которых прописан sсale. И вот на 749px например есть такой перепад в размере между заголовком  и основным текстом. 
UPD 31.10 
Рефакторинг: для более верной верстки хироу секции страницы разбила текущий компонент на два компонента: hero-title и …
> For Press Hero Title: Компонент с заголовком и описанием страницы О прессы

- src/components/for-press-hero-pr-contact/assets/mock-data.json
- src/components/for-press-hero-pr-contact/for-press-hero-pr-contact.module.css
- src/components/for-press-hero-pr-contact/for-press-hero-pr-contact.stories.tsx
- src/components/for-press-hero-pr-contact/for-press-hero-pr-contact.tsx
- src/components/for-press-hero-pr-contact/index.tsx
- src/components/project-header/project-header.module.css
Компонент страницы Для прессы рендерит информацию о PR-контактах фестиваля. 
[Компонент for-press-hero-pr-contact](https://www.notion.so/for-press-hero-pr-contact-eacbe912b7e64e7481e299390fedded2)
Резиновость прописываю от 1440px, но в целом пока по шрифтам все некрасиво едет, похоже из-за того, что подход не унифицирован. 
Использовала семантические теги` dl, dt, dd`. Как считаете, обоснованно ли? 
В целом предлагаем, что информация в целом статичная, но на всякий случай все же прописываю, что информации о персоне может меняться. Как считаете, не нужно ли весь текст просто захардкодить?
> For press hero pr contact

- src/shared/fetcher.ts
Vercel переписывает `NODE_ENV` переменную, если я пытаюсь сказать что нужно быть `development`
Как временное решение - можно использовать моки вообще всегда, но надо не забыть вернуть как было, когда будут ендпоинты.
> fix: ugly hack to make fetcher work on Vercel

- src/shared/hooks/use-media-query.ts
Добавлена поддержка Safari <14 в useMediaQuery
https://lubimovka-frontend-akejmymx5-lubi.vercel.app/
[Пофиксить баг с mediaQueryList в сафари](https://www.notion.so/mediaQueryList-f50f4078ac1640d6846720713de87a49)
> Добавлена поддержка Safari <14 в useMediaQuery

- src/components/footer/footer.module.css
- src/components/footer/footer.tsx
- src/components/ui/menu/type/footer-navigation.module.css
- src/components/ui/menu/type/footer-project-list.module.css
* Исправила баг с повторной отрисовкой блоков футера _(дважды рендерились не только партнеры, но и блоки адреса, навигации, проектов - от этого шрифты казались жирнее)_
* переписала ссылки в Footnote, используя компонент InfoLink (в т.ч. за ради ховер)
[Исправить верстку футера](https://www.notion.so/cb43e5fac4cb4df7b5d28f7d60a5a53f)
> Исправление верстки футера

- src/components/ui/tag/tag.module.css
- src/components/ui/tag/tag.stories.tsx
- src/components/ui/tag/tag.tsx
Сделал рефакторинг компонента Tags. Добавил возможность добавления иконки крестика в компонент в соответствии с изменением дизайна. Добавил в пропсы функцию колбэк - которая срабатывает при нажатии на иконку.
[Refactoring tags](https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=948f9071c27840768796e3c0a8fc7311)
> refactoring: added icon in tags and props cb and isIcon

- src/components/ui/basic-play-card/basic-play-card.module.css
- src/components/ui/basic-play-card/basic-play-card.stories.tsx
- src/components/ui/basic-play-card/basic-play-card.tsx
- src/shared/styles/mixins/truncated-text.css
Добавление функционала в BasicPlayCard для рендеринга нескольких авторов пьесы 
Предполагаю, что авторы приходят в массиве объектов, состоящим из id + имя. 
@borodulex Илья, так как появился дополнительный элемент (список авторов со своей шириной), для корректного отображения вернула ширину в стили .container. Знаю, что много обсуждала. Но сегодня на демо также поняла, что ширина компонента часто не совсем верная, а хотелось бы контролировать. Все комментарии принимаю 🙌
05.11
Поправлен стиль на ховер для ссылки с автором
08.11
Поправила именования свойств в интерфейсе (соответствуют данным, которые приходят с бэка)
> basic-play-card: рендеринг нескольких авторов

- src/pages/library/index.tsx
Обновить мок-карточку для пьес библиотеки
Задачи нет, небольшие изменения, чтобы страница library собиралась без ошибок, т.к. изменилась структура у пропсов BasicPlayCard
> fix: обновить мок-карточку для пьес библиотеки

- src/components/library-pieces-page/index.tsx
- src/components/library-pieces-page/library-filters-modal/index.module.css
- src/components/library-pieces-page/library-filters-modal/index.tsx
- src/components/library-tags-mobile/library-tags-mobile.tsx
https://www.notion.so/Front-52aae4efcc1743f58f4abf64bf7357ff?p=cb14aabe5673422b99df49e60b1a95ca
1. Исправила реализацию верстки модального окна с фильтрами - сохраняются года при закрытии/открытии модального окна
2. Удаление элемента года из стейта и из списка выбранных годов компонента droplist
> Fix library filter year

- src/components/author-page/overview/overview.tsx
- src/components/author-page/request/request.tsx
- src/components/contacts-authors/contacts-authors.module.css
- src/components/contacts-authors/contacts-authors.tsx
- src/components/contacts-title/contacts-title.tsx
- src/components/donation-page/report/report.tsx
- src/components/for-press-hero/for-press-hero-pr-contact/for-press-hero-pr-contact.tsx
- src/components/team-page/volunteers/section/volunteers-section.tsx
- src/components/trustees-section/trustees-section.tsx
- src/components/ui/info-link/info-link.stories.tsx
- src/components/ui/text-area/text-area.module.css
- src/pages/contacts/contacts.tsx
Исправляет баги на странице обратной связи
- исправлена пуктуационная ошибка`Если вам есть, чем поделиться...` =>  `Если вам есть чем поделиться...`
- добавлен пробел `согласиена обработку персональных данных` => `согласие на обработку персональных данных`
- поле Текста сообщения теперь тянется только вертикально
- адрес электронной почты переписан с использованием компонента `InfoLink`, описывающий соответствующую анимацию ховера
- скроллбар и ресайзер стилизован в одном стиле с остальными скроллбарами на сайте
также попутно исправлены гиперссылки `mailto://${email}` => `mailto:${email}`
- [На странице "Контакты" в тексте заголовка допущена пунктуационная ошибка. После "есть" убрать запятую](https://www.notion.so/ba35a730bd1148fd9f4c537a23354224)
- [На странице "Контакты" текст пояснения …
> Исправление багов на странице обратной связи

- src/components/project-layout/storey/project-layout-storey.module.css
- src/components/ui/project-card/project-card.module.css
- src/pages/projects/[id].tsx
- добавлены данные с сервера: интро проекта, роли персоны, авторы пьесы
- убраны боковые отступы блока с фотографиями, добавлен нижний отступ блока о сотрудничестве
также попутно приведены в соответствие с макетом: блок о сотрудничестве (`.holder`) и боковые отступы секций на планшетах/мобильных
- [На странице проекта не отображаются короткое интро](https://www.notion.so/331e3b363ba8462695d2f68e51e7cc09)
- [На странице проекта в блоке персон не отображается роль персоны](https://www.notion.so/9a140b68fbf04f6092f76a62fe475d6a)
- [На странице проекта изображения в блоке с изображениями отображаются с отступами слева и справ от края браузера](https://www.notion.so/985be13c7ba642a59b42190e03f47548)
- [На странице проекта блок "Проект открыт к сотрудничеству..." расположен с маленьким отступом …
> Исправление багов на странице проекта

- src/components/performance-crew/performance-crew.tsx
- src/pages/performances/[id].tsx
- src/shared/types/domain.ts
исправляет баг, связанных с невозможностью перейти на страницу спектакля,
корректно отрисовывает блок команды на странице спектакля
[Не осуществляется переход на страницу Спектакль — Performance page путем страница проекты — спектакли — о спектакле](https://www.notion.so/Performance-page-4c8026cee2ea4b6e8fcd985b5e783391)
[Не осуществляется переход на страницу Спектакль — Performance page путем страница афиша — о спектакле](https://www.notion.so/Performance-page-541a2bf87c7c465abe2c342d020b9a13)
** не могу проверить переход по соответствующим ссылкам:
1. на странице /main, т.к. отсутствует блок со спектаклями (похоже с сервера не приходит данных ни об одном спектакле)
2. на странице /afishe, т.к. ссылки отсутствуют
> Исправление передачи данных в блок команды спектакля

- src/components/library-pieces-page/index.module.css
- src/components/library-pieces-page/index.tsx
- src/components/library-pieces-page/library-preloader/library-preloader.tsx
Уменьшает размер gif-картинки preloader'а на странице библиотеки
[Поправить прелоадер библиотеки](https://www.notion.so/76acbe25aaac45adbc584ecf218b8b66)
> fix: уменьшить размер preloader'а на странице библиотеки

- src/components/ui/announced-play-card/announced-play-card.module.css
Убирает фиксированную ширину в контейнере кнопок
[В компоненте announced-play-card убрать фиксированную ширину в контейнере кнопок ](https://www.notion.so/announced-play-card-4fc2c70a8e9c48a19e309907088a0efa)
> style: убрал фиксированную ширину в контейнере кнопок

- src/components/library-pieces-page/index.module.css
Исправления замечания от QA: https://www.notion.so/5d6b8df5e8d0466da3d941d0cc84b789
В фильтрах при переполнении элементов программы, отсутствовал скрол.
Для проверки переполнение в программах, дополнительные элементы клонировать вручную.
[Добавить скролл в sticky фильтры в библиотеке](https://www.notion.so/sticky-f461ddb95b7f43ed88bb198c9037688a)
> style: реализовать скролл в фильтрах при переполнении элементов

- src/pages/library/search-result/index.module.css
Добавляет scroll и sticky для букв в авторах.
Буквы будут фиксироваться, а если их больше высоты экрана, то еще и скролиться.
[Добавить sticky для буквы в авторах](https://www.notion.so/sticky-ea8b3cd707774426a8088c63bcd5dece)
> style: добавить scroll и sticky для букв в авторах

- src/components/project-layout/storey/project-layout-storey.module.css
- src/components/project-layout/storey/project-layout-storey.tsx
- src/pages/projects/[id].tsx
Удален блок «Проект открыт к сотрудничеству»
[Убрать блок «Проект открыт к сотрудничеству»](https://www.notion.so/790ed8be65ce47aeaa0969257bc3951e)
Я не стала удалять сам project-layout-storey_wrapper, чтобы сохранить отступы (предыдущий блок переиспользуется во многих других местах) и на случай проектов, в котором этот блок может понадобиться.
> Удаление блока Проект открыт к сотрудничеству

- src/pages/about-us/ideology/index.tsx
- src/pages/about-us/team/index.tsx
- src/pages/about-us/trustees/index.tsx
- src/pages/blog/blog.tsx
- src/pages/contacts/contacts.tsx
- src/pages/donation/index.tsx
- src/pages/events/index.tsx
- src/pages/form/form.tsx
- src/pages/form/success.tsx
- src/pages/history/index.tsx
- src/pages/library/authors.tsx
- src/pages/library/index.tsx
- src/pages/library/search-no-result/index.tsx
- src/pages/library/search-result/index.tsx
- src/pages/news/news.tsx
- src/pages/performances/[id].tsx
- src/pages/press-releases/[year].tsx
- src/pages/projects/projects.tsx
Добавляет заголовки страниц и прочую мета-информацию (где это возможно) на всех страницах сайта.
[Добавить заголовки страниц.](https://www.notion.so/f361f7c8bd7f492eb2c0c94ff29b0db4)
> Добавление мета-информации на страницы сайта

- src/components/history-page/itself/history-itself.tsx
- Исправлен текст в последней фразе на странице 'История'. 
- Для ссылки "здесь" поправлен атрибут href.
[Ссылка на задачу](https://www.notion.so/35faea77a71242deba9633f091f2ae64)
> Замена ссылки и текста на странице "История"

- src/components/404/NotFoundError.tsx
- src/components/app-layout/app-layout.tsx
Добавлена зависимость от статуса фестиваля для кнопки "Подать пьесу" на страницах 404 и в мобильном меню (layout-menu)
[Важно! Кнопка Подать пьесу на странице 404 не нужна в то время, когда прием пьес закрыт](https://www.notion.so/404-2f93524d060e45708f81fa34f5383eee)
> Скрытие кнопок подачи пьесы, если прием пьес закрыт

- src/components/app-layout/app-layout.tsx
- src/components/partner-card/partner-card.module.css
- src/components/partner-card/partner-card.tsx
- src/core/partner/types.ts
- src/pages/main/main.tsx
- src/services/api/partners.ts
- Добавлены отсутствующие стили для класса description
- Добавлено свойство description в type и api для партнеров
- Исправлен баг с выводом на главной странице всех партнеров (вместо всех отображались только партнеры с флагом is_general: false)
- Описание для партнера выводится только при его наличии, а так же если в карточке есть пропс description
[Для Партнеров не отражаются наименования под логотипом](https://www.notion.so/8edab21581424af79446f4b8ff75f267)
> Приведение карточки партнера к дизайну

- src/pages/performances/[id].tsx
В соответствии с новым форматом продолжительности пьесы (по нашей просьбе бэкендеры изменили отдачу времени пьесы в секундах) добавлен вывод даты в уже форматированном виде при помощи date-fns для чего я сделал небольшую функцию, которая проверяет наличие этого времени и в случае успеха отдает продолжительность в нужном формате
[Исправить продолжительность на странице спектакля](https://www.notion.so/276d6d3f95a14d3d8a8a290bf97b41f6)
> Исправить продолжительность на странице спектакля

- src/components/image-gallery/image-gallery.module.css
- src/components/image-gallery/image-gallery.tsx
- src/pages/performances/[id].tsx
На странице о спектакле отображается заголовок галереи если он есть
[Исправить заголовок блока изображений конструктора](https://www.notion.so/4b33530b19c44b1aa1151e3bd16a486a?v=84023778e1024506b75f0af4321bfba2&p=73d98cef13a645eaa0bd33a0114bc788&pm=s)
> Добавление заголовка галереи спектакля

- src/components/history-page/itself/history-itself.tsx
Заменяет ссылку на журнал на странице "История"
[Заменить ссылку на странице «История»](https://www.notion.so/ab25c69830d44983ae08be9e12cfc7c2)
> fix: замена ссылки на странице История

- src/pages/form/form.tsx
Поле ввода "Название" пьесы в форме ограничено 200 символами. При вводе более 200 символов браузер отображает сообщение об ошибке.
[При вводе более 200 символов в поле “Название” на странице формы подачи пьесы ошибка не появляется](https://www.notion.so/200-722ec59e6cc34c72b696f4e66094b0ca)
> fix: поле Название в форме ограничено 200 символами

- src/pages/contacts/contacts.tsx
- src/services/fetcher/fetcher.ts
Исправление кнопки отправки формы на странице контакты
[На странице контакты. При нажатии кнопки "Отправить" ничего не происходит](https://www.notion.so/a04d4eec813d48ab99b839ecedc0552a?pvs=4)
> fix: исправление кнопки отправки формы на странице контакты

- src/pages/form/form.tsx
- src/services/fetcher/fetcher.ts
При корректном заполнении всех полей формы подачи пьесы ошибка 500. Ошибка пофиксилась в другом пул реквесте, ошибка была в функции handleResponse (fetcher.ts) в строчке "const payload = await response.json();", т.к. сервер при POST запросе на /feedback/participation/ в ответе ничего не возвращает. Так же в этом пул реквесте исправлено то, что номер телефона не попадал в сабмит и возможность отправки формы, не до конца ее заполнив, нажатием Enter.
[При корректном заполнении всех полей формы подачи пьесы ошибка 500](https://www.notion.so/500-4ca806fd7b9244e8bb77f5198d105ffe)
> fix: ошибка 500 при сабмите формы отправки пьесы

- src/shared/constants/regexps.ts
На странице контакты. В поле “Е-mail для ответа” если вести кириллицу сайт зависает. Ошибка в регулярном выражении, валидирующем email, заменил регулярку.
[На странице контакты. В поле “Е-mail для ответа” если вести кириллицу сайт зависает.](https://www.notion.so/mail-0f1a1b45930841009c1ada5c8175c10d)
> fix: ошибка при валидации email

- src/components/ui/menu/type/main-navigation.module.css
Цвет шрифта #000000 вместо #242424 в хэдере страницы конкретного блога. Изменил цвет шрифта.
[Цвет шрифта #000000 вместо #242424 в хэдере страницы конкретного блога](https://www.notion.so/000000-242424-eec1902f94e64f26a93fd6dbae7910f5)
> fix: изменен цвет шрифта для ссылок в хедере

- src/components/app-layout/app-layout.tsx
- src/components/seo/seo.tsx
Страница Блога отображает среднюю часть body при смене ориентации экрана с альбомной на портретную и на альбомную (при изначальном отображении на экране нижней части страницы). При переходе на альбомную ориентацию экрана страница скролится на позицию, которая была в портретной * на отношение ширины и высоты экрана, что примерно соответствует той позиции, которая была до смены ориентации экрана.
[Страница Блога отображает среднюю часть body при смене ориентации экрана с альбомной на портретную и на альбомную (при изначальном отображении на экране нижней части страницы)](https://www.notion.so/body-5f941a0d1d2c4e628a38cfbced8970c5)
> fix: исправлено поведение при смене ориентации экрана

- src/__generated__/api-typings/index.ts
- src/__generated__/api-typings/models/ParticipationRequest.ts
- src/__generated__/api-typings/models/QuestionRequest.ts
- src/components/constructor-content/constructor-content.tsx
- src/components/ui/button2/button.module.css
Исправление конструктора (constructor-content.tsx) в части событий (EvetCard) 
Задачи в notion вроде бы нет.
> fix: Исправление конструктора (constructor-content.tsx) в части событий (EvetCard)

- src/components/blog-entry-card/blog-entry-card.module.css
- src/components/constructor-content/variant/default.module.css
На странице Блог центрирует контент.
Основной текст и заголовки переносятся на новую строку при достижении границы. При этом очень-длинное-слово (набор слов без пробелов) также переносится.
[Страница Блог скукоживается на мобилке](https://www.notion.so/7b2bb17fb3084bda9da5b57f0eda9451)
> fix: исправлен модуль entry-card

- src/components/play-card/play-card.module.css
- src/components/play-list/play-list.module.css
Не помещаются на экране первые два превью в блоке пьес на странице конкретного блока для мобильного устройства. Исправил стили в блоке пьес конкретного блога.
[Не помещаются на экране первые два превью в блоке пьес на странице конкретного блока для мобильного устройства](https://www.notion.so/23ab7f104db34e81a1e7a4f95bbae592)
> fix: исправлены стили в блоке пьес на странице конкретного блога

- src/components/footer/footer.module.css
- src/components/footer/footer.tsx
Не происходит переход на главную страницу при клике на лого в футере страницы блога. Лого в футере обернуто в ссылку на главную страницу.
[Не происходит переход на главную страницу при клике на лого в футере страницы блога](https://www.notion.so/5ebaafc679a34b24aba55666670a9e03)
> fix: логотип в футере сделан ссылкой, ведущей на главную

- cypress.config.ts
- cypress/e2e/city-input.cy.ts
- cypress/e2e/email-input.cy.ts
- cypress/e2e/first-name-input.cy.ts
- cypress/e2e/last-name-input.cy.ts
- cypress/e2e/phone-input.cy.ts
- cypress/e2e/title-input.cy.ts
- cypress/e2e/year-birth-input.cy.ts
- cypress/e2e/year-play-input.cy.ts
- cypress/fixtures/test-constants.json
- cypress/support/commands.ts
- cypress/support/e2e.ts
- src/pages/form/form.tsx
Данный пулл-реквест содержит тесты для полей ввода формы подачи пьесы.
Тесты проверяют наличие сообщения об ошибке при вводе некорректных данных и отсутствие такого сообщения при вводе корректных данных (для каждого поля в отдельности).
[Написать e2e-тесты](https://www.notion.so/e2e-10897b6836094aa4b5db29820e50d043)
1) При тестировании полей ввода Телефона и E-mail (а они валидируются в компонентом с применением регулярных выражений), при вводе некорректных данных сообщение об ошибке выдает только E-mail.
2) Пока не понятно, как сделать тест активации (деактивации) кнопки отправки заявки (submit-button).
3) Пока не понятно, как сделать тест для загрузки и отправки прикрепленного файла.
> feat: добавлены тесты для полей ввода формы подачи пьесы

- src/components/blog-entry-card/blog-entry-card.module.css
Можно перейти на страницу блога из раздела Блог Любимовки кликнув по фотографии в карточке в браузере Firefox. Исправлено.
[Можно перейти на страницу блога из раздела Блог Любимовки кликнув по фотографии в карточке в браузере Firefox](https://www.notion.so/Firefox-050a1e358a2a4d97b084054c59c2ab4c)
> fix: исправлено открытие блога при клике по фотографии

- src/components/author-list/item/author-list-item.module.css
- src/components/library-layout/library-layout.module.css
- src/components/page/navbar/page-navbar.module.css
- src/components/play-card/play-card.module.css
- src/components/ui/menu/type/library-navigation.module.css
Исправление стилей для страницы библиотека.  
Исправил шапку и переполнение текста в карточках.
[Привести страницы авторов и пьес в библиотеке к дизайну](https://www.notion.so/1622363f3290431f95cd462e2d1ab082?pvs=4)
> fix: исправление стилей для страницы библиотека

- src/components/author-page/overview/overview.tsx
Этот Pull Request исправляет поведение ссылок на странице авторов. Теперь при клике на ссылки социальных сетей они открываются в новой вкладке.
[Открытие ссылок соцсетей в новых вкладках#552](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/552#issue-2423903651 )
> fix: исправить открытие ссылок соцсетей на странице авторов

- src/components/history-page/title/history-title-card.tsx
- src/components/history-page/title/history-title.module.css
[Некорректный курсор на не ссылках. #561](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/561)
Обновлен стили и компоненты так, чтобы курсор менялся на указатель только на элементах, которые действительно являются ссылками. Для остальных элементов курсор оставаться стандартным.
> Feature/issue 561/fix cursor for non links

- src/components/festival-event-card/festival-event-card.module.css
- src/components/festival-event-card/festival-event-card.tsx
- src/components/festival-schedule/festival-schedule.tsx
- src/core/schedule/types.ts
- src/services/api/schedule-adapter.ts
Этот Pull Request исправляет ошибку при которой в афише у спектакля отсутствовала ссылка для перехода на страницу спектакля.
При наведении на заголовок спектакля добавлена визуальная подсказка, что элемент интерактивный.
[Проблема с отображением ссылок на спектакли]( https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/567#issue-2498907970 )
> Bugfix-festival-event-card

- src/components/donation-link/donation-link.module.css
- src/components/donation-link/donation-link.tsx
[Активация кнопки Поддержать при переходе на неё #557](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/557)
При переходе на страницу "Поддержать", кнопка корректно отображается как активная.
Выполнена стилизация в файле CSS через использование класса .link.active.
В Компоненте реализовано хук useRouter из next/router, чтобы определить текущий маршрут (router.asPath).
> Feature/issue 557/donation rout active style

- src/components/history-page/title/history-title.tsx
- src/pages/about-us/sponsors/index.tsx
- src/pages/about-us/team/index.tsx
- src/pages/history/[year].tsx
- src/services/api/settings-adapter.ts
[Переход по ссылке на список волонтёров падает с 500 ошибкой. #562](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/562)
Когда show_volunteers равно false: Кнопка с ссылкой на страницу команды не отображается, а поле ведет себя как обычное числовое поле.
Когда show_volunteers равно true: Появляется кнопка со ссылкой на страницу команды.    
Получение значения show_volunteers:
В getServerSideProps компонента Team добавлено извлечение значения show_volunteers из API (/info/settings/).
Значение show_volunteers передается в компонент History и далее в компонент HistoryTitle.
Обработка логики в HistoryTitle:
Компонент HistoryTitle принимает свойство showVolunteers.
В объекте cards добавлен buttonProps только если showVolunteers равно true. Если showVolunteers равно false, …
> Feature/issue 562/hide&show volunteers button settings

- src/pages/contacts/contacts.tsx
[Блокировать кнопку отправки формы на странице контактов. #554](https://github.com/Studio-Yandex-Practicum/lubimovka_frontend/issues/554)
При нажатии на кнопку отправки формы заменяет подпись кнопки на "Отправляется" и блокирует кнопку от повторного нажатия до получения ответа сервера.
> block-submit-button
